### ISSUE TITLE
Black region?

### ISSUE THREAD

**Issue by konrad79** [entorb/COVID-19-Coronavirus-German-Regions#5]
What is this always black region within the LK Eisenach?
![2021-11-29 07_59_07-COVID-19 Coronavirus Disease Spread Analysis in German Regions and the World — M](https://user-images.githubusercontent.com/31411681/143822323-1b651529-02be-4c16-a894-3c39ddc76edb.png)

**Comment by entorb** [comment]
Hi you are right. the LK Eisenach was merged with the neighbor, see [here](https://www.eisenach.de/rathaus/fusion-der-stadt-eisenach). I should fix this in the map, thanks for pointing out!

**Comment by konrad79** [comment]
Top! Und faszinierend :-)
